name: .Net 7 CI Build

on:
  workflow_dispatch:
  push:
    branches:
    - main
    
env:
 SOLUTION_Path: ./CleanArchitecture.sln

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Restore Dependencies
      run: dotnet restore ${{ env.SOLUTION_Path }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_Path }} --configuration Release --no-restore

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '40 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
